// Shared by both browser engines. Provider branding, navigation and players stay owned by the service.
var profiles = {
    netflix: {domains:["netflix.com"],kind:"watch",css:".mainView{min-height:calc(100vh - 70px)}"},
    prime: {domains:["primevideo.com","amazon.com","amazon.in","amazon.co.uk"],kind:"watch",css:"main{min-height:80vh}"},
    disney: {domains:["disneyplus.com","hotstar.com"],kind:"watch",css:"main{min-height:80vh}"},
    hbomax: {domains:["hbomax.com","max.com"],kind:"watch",css:"main{min-height:80vh}"},
    appletv: {domains:["tv.apple.com"],kind:"watch",css:"main{min-height:80vh}"},
    crunchyroll: {domains:["crunchyroll.com"],kind:"watch",css:"main{min-height:80vh}"},
    youtube: {domains:["youtube.com","youtu.be"],kind:"watch",css:"ytd-app{--ytd-rich-grid-item-min-width:260px;--ytd-rich-grid-item-max-width:380px}ytd-rich-grid-renderer{max-width:none!important}#guide #footer{display:none!important}"},
    hulu: {domains:["hulu.com"],kind:"watch",css:"main{min-height:80vh}"},
    mubi: {domains:["mubi.com"],kind:"watch",css:"main{min-height:80vh}"},
    spotify: {domains:["open.spotify.com"],kind:"listen",css:".Root__main-view{overscroll-behavior:contain}"},
    ytmusic: {domains:["music.youtube.com"],kind:"listen",css:"ytmusic-app{min-height:100vh}ytmusic-browse-response{max-width:none!important}"},
    applemusic: {domains:["music.apple.com"],kind:"listen",css:"main{min-height:80vh}"},
    kindle: {domains:["read.amazon.com","read.amazon.in","read.amazon.co.uk"],kind:"read",css:"#kindleReader_content{overscroll-behavior:contain}"},
    playbooks: {domains:["play.google.com","books.google.com"],kind:"read",css:"[role=main]{min-height:80vh}"},
    mangaplus: {domains:["mangaplus.shueisha.co.jp"],kind:"read",css:"main{margin-inline:auto}"},
    viz: {domains:["viz.com"],kind:"read",css:"main{margin-inline:auto}"},
    webtoon: {domains:["webtoons.com"],kind:"read",css:"#_webtoonDArea{margin-inline:auto}#_webtoonDArea img{max-width:100%}"},
    dcui: {domains:["dcuniverseinfinite.com"],kind:"read",css:"main{min-height:80vh}"},
    kobo: {domains:["kobo.com","kobobooks.com"],kind:"read",css:"main{min-height:80vh}"}
};

var installSource = [
    "function install(profile, layout, keyboard, accent) {",
    "    var previous = window.__feriaAppMode;",
    "    function clear() {",
    "        var style = document.getElementById(\"feria-app-layout\");",
    "        if (style) style.remove();",
    "        document.documentElement.removeAttribute(\"data-feria-app\");",
    "        if (previous) document.removeEventListener(\"keydown\", previous.keydown, true);",
    "        window.__feriaAppMode = null;",
    "    }",
    "    var host = location.hostname.toLowerCase();",
    "    var allowed = (profile.domains || []).some(function(domain) { return host === domain || host.endsWith(\".\" + domain); });",
    "    var auth = /\\/(login|signin|sign-in|signup|sign-up|register|auth|checkout|payment|billing|subscribe|subscription|purchase|consent|challenge|captcha|legal|terms|privacy)(\\/|$)/i.test(location.pathname)",
    "        || Array.prototype.some.call(document.querySelectorAll('input[type=\"password\"],input[autocomplete=\"one-time-code\"],[role=\"dialog\"][aria-modal=\"true\"]'),function(node) {",
    "            var rect = node.getBoundingClientRect(), css = getComputedStyle(node);",
    "            return rect.width > 0 && rect.height > 0 && css.visibility !== \"hidden\" && css.display !== \"none\" && css.opacity !== \"0\" && !node.closest('[hidden],[aria-hidden=true]');",
    "        });",
    "    if (!allowed || auth || (!layout && !keyboard)) { clear(); return {adapted:false}; }",
    "    var signature = JSON.stringify([profile.id, layout, keyboard, accent]);",
    "    if (previous && previous.signature === signature && (!layout || document.getElementById(\"feria-app-layout\"))) return {adapted:true};",
    "    clear();",
    "    if (layout) {",
    "        document.documentElement.setAttribute(\"data-feria-app\",profile.id);",
    "        var style = document.createElement(\"style\");",
    "        style.id = \"feria-app-layout\";",
    "        // Footer/promotional chrome only: never remove provider headers, consent, dialogs or players.",
    "        style.textContent = 'html[data-feria-app]{overscroll-behavior:none;scroll-padding:24px}'",
    "            + 'html[data-feria-app] :is(a,button,input,select,textarea,[tabindex]):focus-visible{outline:3px solid '+accent+'!important;outline-offset:3px!important}'",
    "            + 'html[data-feria-app] :is(footer,[role=contentinfo]):not([id*=cookie]):not([class*=cookie]):not(:has(button,input,form,[role=dialog],[role=checkbox],[class*=cookie],[id*=cookie],[data-testid*=consent])){display:none!important}' + (profile.css || \"\");",
    "        document.head.appendChild(style);",
    "    }",
    "    function keydown(event) {",
    "        if (!keyboard || event.defaultPrevented || event.altKey || event.ctrlKey || event.metaKey || event.shiftKey",
    "            || [\"ArrowLeft\",\"ArrowRight\",\"ArrowUp\",\"ArrowDown\"].indexOf(event.key) < 0) return;",
    "        // Leave text editing, modal widgets and provider player shortcuts intact.",
    "        var active = document.activeElement;",
    "        var target = event.target;",
    "        var owned = 'input,textarea,select,[contenteditable=true],[role=slider],[role=spinbutton],[role=combobox],[role=listbox],[role=menu],[role=tablist],[role=dialog],video,audio,.html5-video-player,[data-testid*=player]';",
    "        if ((target && (target.isContentEditable || (target.closest && target.closest(owned))))",
    "            || (active && (active.isContentEditable || (active.closest && active.closest(owned))))) return;",
    "        if (profile.kind === \"read\" && (/\\/(reader|viewer|chapter|episode)(\\/|$)/i.test(location.pathname)",
    "            || /(asin|book|volume)=[^&]+/i.test(location.search || \"\") || document.querySelector('[data-reader],#reader,#kindleReader_content,#_webtoonDArea'))) return;",
    "        var playerRoute = /\\/(watch|player|play|video|shorts)(\\/|$)/i.test(location.pathname) || !!document.fullscreenElement;",
    "        if (profile.kind === \"watch\" && playerRoute && Array.prototype.some.call(document.querySelectorAll(\"video,audio\"),function(media) { return !media.paused && !media.ended; })) return;",
    "        var controls = Array.prototype.filter.call(document.querySelectorAll('a[href],button,input:not([type=hidden]),select,textarea,[role=button],[role=link],[tabindex]:not([tabindex=\"-1\"])'),function(node) {",
    "            if (node.disabled || node.getAttribute(\"aria-disabled\") === \"true\" || node.getAttribute(\"tabindex\") === \"-1\"",
    "                || node.closest('[hidden],[inert],[aria-hidden=true]')) return false;",
    "            var rect = node.getBoundingClientRect(), css = getComputedStyle(node);",
    "            return rect.width > 0 && rect.height > 0 && rect.bottom > 0 && rect.top < innerHeight",
    "                && rect.right > 0 && rect.left < innerWidth && css.visibility !== \"hidden\" && css.display !== \"none\";",
    "        });",
    "        if (!controls.length) return;",
    "        var next = null, best = Infinity;",
    "        var origin = active && controls.indexOf(active) >= 0 ? active.getBoundingClientRect() : null;",
    "        if (!origin) next = controls[0];",
    "        else {",
    "            var horizontal = event.key === \"ArrowLeft\" || event.key === \"ArrowRight\";",
    "            var direction = event.key === \"ArrowLeft\" || event.key === \"ArrowUp\" ? -1 : 1;",
    "            controls.forEach(function(node) {",
    "                if (node === active) return;",
    "                var rect = node.getBoundingClientRect();",
    "                var dx = rect.left + rect.width/2 - (origin.left + origin.width/2);",
    "                var dy = rect.top + rect.height/2 - (origin.top + origin.height/2);",
    "                var along = (horizontal ? dx : dy) * direction;",
    "                var across = Math.abs(horizontal ? dy : dx);",
    "                if (along <= 1) return;",
    "                var score = along + across * 3;",
    "                if (score < best) { best = score; next = node; }",
    "            });",
    "        }",
    "        if (!next) return; // Preserve page scrolling at the edge of visible content.",
    "        next.focus({preventScroll:true});",
    "        next.scrollIntoView({block:\"nearest\",inline:\"nearest\",behavior:\"auto\"});",
    "        event.preventDefault();",
    "        event.stopPropagation();",
    "    }",
    "    document.addEventListener(\"keydown\",keydown,true);",
    "    window.__feriaAppMode = {signature:signature,keydown:keydown};",
    "    return {adapted:true};",
    "}"
].join("\n");

function scriptForProfile(profile, layout, keyboard, accent) {
    accent = /^#[0-9a-f]{6}$/i.test(accent || "") ? accent : "#f2c94c";
    return "(" + installSource + ")(" + JSON.stringify(profile) + "," + JSON.stringify(layout === true)
        + "," + JSON.stringify(keyboard === true) + "," + JSON.stringify(accent) + ")";
}
function script(provider, layout, keyboard, accent) {
    var profile = profiles[provider] || {domains:[]};
    var config = {id:provider,domains:profile.domains || [],kind:profile.kind || "watch",css:profile.css || ""};
    return scriptForProfile(config,layout,keyboard,accent);
}
