// EpubTextIndexer harness — proves the C++ indexer reproduces the shared canonical
// oracle (tests/fixtures/alignment/canonical/expected.json), which was generated by
// the REAL alignment_text.js. C++ matching it == C++/JS canonical parity.
//
// Usage: epub_text_indexer_harness [fixture.epub expected.json]
//   With no args, falls back to ALIGNMENT_CANONICAL_DIR (set by CMake).
// Verdict via exit code (0 PASS / 1 FAIL).

#include "alignment/EpubTextIndexer.h"

#include <QCoreApplication>
#include <QFile>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <cstdio>

using namespace alignment;

static bool g_failed = false;
static void check(bool ok, const char *msg) {
    if (!ok) { std::fprintf(stderr, "FAIL: %s\n", msg); g_failed = true; }
}

int main(int argc, char **argv) {
    QCoreApplication app(argc, argv);

    QString epubPath, expectedPath;
    if (argc >= 3) {
        epubPath = QString::fromLocal8Bit(argv[1]);
        expectedPath = QString::fromLocal8Bit(argv[2]);
    } else {
#ifdef ALIGNMENT_CANONICAL_DIR
        const QString dir = QStringLiteral(ALIGNMENT_CANONICAL_DIR);
        epubPath = dir + QStringLiteral("/fixture.epub");
        expectedPath = dir + QStringLiteral("/expected.json");
#else
        std::fprintf(stderr, "FAIL: no fixture paths given and ALIGNMENT_CANONICAL_DIR undefined\n");
        return 1;
#endif
    }

    QFile ef(expectedPath);
    if (!ef.open(QIODevice::ReadOnly)) { std::fprintf(stderr, "FAIL: cannot open %s\n", qPrintable(expectedPath)); return 1; }
    const QJsonObject expected = QJsonDocument::fromJson(ef.readAll()).object();
    ef.close();

    EpubTextIndexer indexer;
    const EpubIndex idx = indexer.index(epubPath);
    check(idx.ok, "index ok");
    if (!idx.ok) { std::fprintf(stderr, "  error: %s\n", qPrintable(idx.error)); return 1; }
    check(idx.documents.size() == 1, "one spine document indexed");
    if (idx.documents.isEmpty()) return 1;

    const SpineDocument &doc = idx.documents.first();
    check(doc.href == expected.value(QStringLiteral("spineHref")).toString(), "spine href matches");

    const QString expCanonical = expected.value(QStringLiteral("canonical")).toString();
    check(doc.canonical == expCanonical, "canonical stream matches oracle");
    if (doc.canonical != expCanonical) {
        std::fprintf(stderr, "  got:  %s\n", qPrintable(doc.canonical));
        std::fprintf(stderr, "  want: %s\n", qPrintable(expCanonical));
    }

    // Sentences: count, boundaries, and per-sentence SHA-256.
    const QJsonArray expSentences = expected.value(QStringLiteral("sentences")).toArray();
    check(doc.sentences.size() == expSentences.size(), "sentence count matches");
    for (int i = 0; i < expSentences.size() && i < doc.sentences.size(); ++i) {
        const QJsonObject es = expSentences.at(i).toObject();
        const IndexedSentence &gs = doc.sentences.at(i);
        check(gs.canonicalStart == es.value(QStringLiteral("canonicalStart")).toInt(),
              qPrintable(QStringLiteral("sentence %1 canonicalStart").arg(i)));
        check(gs.canonicalEnd == es.value(QStringLiteral("canonicalEnd")).toInt(),
              qPrintable(QStringLiteral("sentence %1 canonicalEnd").arg(i)));
        check(gs.sentenceHash == es.value(QStringLiteral("sentenceHash")).toString(),
              qPrintable(QStringLiteral("sentence %1 sha256 hash").arg(i)));
    }

    // The canonical->display offset map is each side's OWN bridge to its OWN display
    // representation: the C++ indexer maps into the packaged XHTML text (markup
    // whitespace included), the JS resolver maps into the live DOM. They are NOT the
    // same string, so the map values legitimately differ — the display-INVARIANT
    // contract (canonical stream + sentence offsets + hashes) is what must agree.
    // Here we assert the C++ map is self-consistent: one entry per canonical char,
    // every entry a valid index into this document's own displaySource.
    check(doc.map.size() == doc.canonical.size(), "map has one entry per canonical char");
    bool mapInRange = true;
    for (int k = 0; k < doc.map.size(); ++k)
        if (doc.map.at(k) < 0 || doc.map.at(k) >= doc.displaySource.size()) { mapInRange = false; break; }
    check(mapInRange, "every map entry is a valid displaySource index");

    if (g_failed) return 1;
    std::fprintf(stdout, "PASS canonical text and offsets agree\n");
    return 0;
}
