import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const scope = vm.createContext({});
vm.runInContext(fs.readFileSync(new URL('../qml/feria/FeriaPlayback.js', import.meta.url), 'utf8'), scope);
assert.equal(scope.sameDestination('https://provider.test/watch?id=1', 'https://provider.test/watch?id=1'), true);
assert.equal(scope.sameDestination('https://provider.test/login', 'https://provider.test/watch?id=1'), false);
assert.equal(scope.sameDestination('https://provider.test/watch?id=2', 'https://provider.test/watch?id=1'), false);
assert.equal(scope.sameDestination('https://provider.test/#/episode/2', 'https://provider.test/#/episode/1'), false);
const paused = {paused:true, duration:1000, currentTime:0};
const playing = {paused:false, duration:100, currentTime:5};
scope.document = {querySelectorAll:() => [paused, playing], querySelector:() => null};
assert.equal(vm.runInContext(scope.seek(40), scope), true);
assert.equal(playing.currentTime, 40);
assert.equal(paused.currentTime, 0);
scope.document.querySelector = () => ({});
assert.equal(vm.runInContext(scope.seek(60), scope), false);
assert.equal(playing.currentTime, 40);
console.log('Feria resume destination, active-player selection, and ad guard checks pass');
assert.equal(scope.sameDestination('https://www.netflix.com/watch/123?trackId=9', 'https://www.netflix.com/watch/123'), true);
assert.equal(scope.sameDestination('https://youtube.com/watch?v=abc&utm_source=test', 'https://youtube.com/watch?v=abc'), true);
assert.equal(scope.sameDestination('https://provider.test/read?page=2', 'https://provider.test/read?page=1'), false);
assert.equal(scope.sameDestination('https://other.test/watch?id=1', 'https://provider.test/watch?id=1'), false);
assert.equal(scope.sameDestination('https://provider.test/watch?id=1&edition=B', 'https://provider.test/watch?id=1&edition=A'), false);
scope.document.querySelector = () => null;
const nested = {paused:false, duration:120, currentTime:5, tagName:'VIDEO', ended:false};
const shadow = {querySelectorAll:s => s === 'video,audio' ? [nested] : [], querySelector:() => null};
scope.document.querySelectorAll = s => s === '*' ? [{shadowRoot:shadow}] : [];
assert.equal(vm.runInContext(scope.seek(55), scope), true);
assert.equal(nested.currentTime, 55);
scope.document.querySelectorAll = s => s === 'iframe,frame' ? [{contentDocument:shadow}] : [];
assert.equal(vm.runInContext(scope.seek(65), scope), true);
assert.equal(nested.currentTime, 65);
scope.location = {href:'https://music.test/track/1'};
scope.navigator = {};
assert.equal(vm.runInContext(scope.observation('listen'), scope).kind, 'audio');
scope.document.querySelectorAll = s => s === 'iframe,frame' ? [{get contentDocument(){throw new Error('cross origin');}}] : [];
assert.equal(vm.runInContext(scope.seek(65), scope), false);
scope.location = {href:'https://reader.test/chapter/1'};
scope.navigator = {};
scope.window = {addEventListener:() => {}};
scope.document = {title:'Chapter one', visibilityState:'visible', querySelector:() => null,
    querySelectorAll:() => [], scrollingElement:{scrollTop:500,scrollHeight:2000,clientHeight:1000},
    addEventListener:() => {}};
let reading = vm.runInContext(scope.observation('read'), scope);
assert.equal(reading.kind, 'book');
assert.equal(reading.locator.fraction, 0.5);
assert.equal(vm.runInContext(scope.restoreReading({type:'scroll',selector:'',fraction:0.7}), scope), true);
assert.equal(scope.document.scrollingElement.scrollTop, 700);
scope.location.href = 'https://reader.test/catalog';
assert.notEqual(vm.runInContext(scope.observation('read'), scope).kind, 'book');
console.log('Feria tracking URLs, nested players, reading observation and restore checks pass');
