#pragma once

#include <QHash>
#include <QString>

namespace GenreArt {
// Moved from qml/GenreIndexApi.js:26-110: baked representative manga genre covers.
inline QString manga(const QString &name)
{
    static const QHash<QString, QString> covers{
        {QStringLiteral("Action"), QStringLiteral("https://cdn.myanimelist.net/images/manga/1/157897l.jpg")},
        {QStringLiteral("Adventure"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/253146l.jpg")},
        {QStringLiteral("Avant Garde"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/161311l.jpg")},
        {QStringLiteral("Award Winning"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/216464l.jpg")},
        {QStringLiteral("Boys Love"), QStringLiteral("https://cdn.myanimelist.net/images/manga/1/220586l.jpg")},
        {QStringLiteral("Comedy"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/80661l.jpg")},
        {QStringLiteral("Drama"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/37846l.jpg")},
        {QStringLiteral("Fantasy"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/222295l.jpg")},
        {QStringLiteral("Girls Love"), QStringLiteral("https://cdn.myanimelist.net/images/manga/1/232311l.jpg")},
        {QStringLiteral("Gourmet"), QStringLiteral("https://cdn.myanimelist.net/images/manga/1/115803l.jpg")},
        {QStringLiteral("Horror"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/114037l.jpg")},
        {QStringLiteral("Mystery"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/186922l.jpg")},
        {QStringLiteral("Romance"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/245008l.jpg")},
        {QStringLiteral("Sci-Fi"), QStringLiteral("https://cdn.myanimelist.net/images/manga/5/260006l.jpg")},
        {QStringLiteral("Slice of Life"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/266834l.jpg")},
        {QStringLiteral("Sports"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/258225l.jpg")},
        {QStringLiteral("Supernatural"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/210341l.jpg")},
        {QStringLiteral("Suspense"), QStringLiteral("https://cdn.myanimelist.net/images/manga/1/258245l.jpg")},
        {QStringLiteral("Ecchi"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/172982l.jpg")},
        {QStringLiteral("Erotica"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/178011l.jpg")},
        {QStringLiteral("Adult Cast"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/258224l.jpg")},
        {QStringLiteral("Anthropomorphic"), QStringLiteral("https://cdn.myanimelist.net/images/manga/1/115443l.jpg")},
        {QStringLiteral("CGDCT"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/259651l.jpg")},
        {QStringLiteral("Childcare"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/219741l.jpg")},
        {QStringLiteral("Combat Sports"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/250313l.jpg")},
        {QStringLiteral("Crossdressing"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/267782l.jpg")},
        {QStringLiteral("Delinquents"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/196272l.jpg")},
        {QStringLiteral("Detective"), QStringLiteral("https://cdn.myanimelist.net/images/manga/1/264496l.jpg")},
        {QStringLiteral("Educational"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/200497l.jpg")},
        {QStringLiteral("Gag Humor"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/166124l.jpg")},
        {QStringLiteral("Gore"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/145997l.jpg")},
        {QStringLiteral("Harem"), QStringLiteral("https://cdn.myanimelist.net/images/manga/1/181212l.jpg")},
        {QStringLiteral("High Stakes Game"), QStringLiteral("https://cdn.myanimelist.net/images/manga/1/278020l.jpg")},
        {QStringLiteral("Historical"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/179023l.jpg")},
        {QStringLiteral("Idols (Female)"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/295874l.jpg")},
        {QStringLiteral("Idols (Male)"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/256420l.jpg")},
        {QStringLiteral("Isekai"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/167639l.jpg")},
        {QStringLiteral("Iyashikei"), QStringLiteral("https://cdn.myanimelist.net/images/manga/5/259524l.jpg")},
        {QStringLiteral("Love Polygon"), QStringLiteral("https://cdn.myanimelist.net/images/manga/1/262324l.jpg")},
        {QStringLiteral("Love Status Quo"), QStringLiteral("https://cdn.myanimelist.net/images/manga/1/268387l.jpg")},
        {QStringLiteral("Magical Sex Shift"), QStringLiteral("https://cdn.myanimelist.net/images/manga/1/188806l.jpg")},
        {QStringLiteral("Mahou Shoujo"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/259289l.jpg")},
        {QStringLiteral("Martial Arts"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/249658l.jpg")},
        {QStringLiteral("Mecha"), QStringLiteral("https://cdn.myanimelist.net/images/manga/1/145061l.jpg")},
        {QStringLiteral("Medical"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/201154l.jpg")},
        {QStringLiteral("Memoir"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/180846l.jpg")},
        {QStringLiteral("Military"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/243675l.jpg")},
        {QStringLiteral("Music"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/66993l.jpg")},
        {QStringLiteral("Mythology"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/161911l.jpg")},
        {QStringLiteral("Organized Crime"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/210716l.jpg")},
        {QStringLiteral("Otaku Culture"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/215054l.jpg")},
        {QStringLiteral("Parody"), QStringLiteral("https://cdn.myanimelist.net/images/manga/1/230705l.jpg")},
        {QStringLiteral("Performing Arts"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/209753l.jpg")},
        {QStringLiteral("Pets"), QStringLiteral("https://cdn.myanimelist.net/images/manga/1/182059l.jpg")},
        {QStringLiteral("Psychological"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/188918l.jpg")},
        {QStringLiteral("Racing"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/186990l.jpg")},
        {QStringLiteral("Reincarnation"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/233991l.jpg")},
        {QStringLiteral("Reverse Harem"), QStringLiteral("https://cdn.myanimelist.net/images/manga/1/206834l.jpg")},
        {QStringLiteral("Samurai"), QStringLiteral("https://cdn.myanimelist.net/images/manga/1/259070l.jpg")},
        {QStringLiteral("School"), QStringLiteral("https://cdn.myanimelist.net/images/manga/1/209370l.jpg")},
        {QStringLiteral("Showbiz"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/255389l.jpg")},
        {QStringLiteral("Space"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/170572l.jpg")},
        {QStringLiteral("Strategy Game"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/149018l.jpg")},
        {QStringLiteral("Super Power"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/204842l.jpg")},
        {QStringLiteral("Survival"), QStringLiteral("https://cdn.myanimelist.net/images/manga/1/197883l.jpg")},
        {QStringLiteral("Team Sports"), QStringLiteral("https://cdn.myanimelist.net/images/manga/5/213340l.jpg")},
        {QStringLiteral("Time Travel"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/153742l.jpg")},
        {QStringLiteral("Urban Fantasy"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/252929l.jpg")},
        {QStringLiteral("Vampire"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/269907l.jpg")},
        {QStringLiteral("Video Game"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/228144l.jpg")},
        {QStringLiteral("Villainess"), QStringLiteral("https://cdn.myanimelist.net/images/manga/5/303096l.jpg")},
        {QStringLiteral("Visual Arts"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/204827l.jpg")},
        {QStringLiteral("Workplace"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/155740l.jpg")},
        {QStringLiteral("Josei"), QStringLiteral("https://cdn.myanimelist.net/images/manga/1/262323l.jpg")},
        {QStringLiteral("Kids"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/265951l.jpg")},
        {QStringLiteral("Seinen"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/188925l.jpg")},
        {QStringLiteral("Shoujo"), QStringLiteral("https://cdn.myanimelist.net/images/manga/2/256907l.jpg")},
        {QStringLiteral("Shounen"), QStringLiteral("https://cdn.myanimelist.net/images/manga/3/180031l.jpg")},
    };
    return covers.value(name);
}
} // namespace GenreArt
